Attempt to fix failing CI
This fix now uses pip3.6 explicitly on linux

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,6 +14,10 @@ addons:
       - "python3"
       - "python3-pip"
 
+# Set python version to 3.6
+python:
+  - "3.6"
+
 ##############################################################################
 # branch settings
 ##############################################################################
@@ -257,13 +261,15 @@ install:
   - |
     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update
-      brew install cmake ninja python3
-      brew upgrade cmake python3
+
+      # Some OSX versions fail if already installed, so || this with true
+      brew install cmake ninja python3 || true
+      brew upgrade cmake python3 || true
     fi
 
   # Install conan
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install conan; fi
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3 -m pip install conan; fi
+  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install --user conan fi
+  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3.6 install --user conan fi
 
 ##############################################################################
 # 2. Build Step
@@ -286,7 +292,7 @@ script:
   - $CXX --version
   - cmake --version
   - ninja --version
-  - python --version
+  - python3 --version
   - conan --version
 
   # Compile and execute unit tests
